source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

def reusepods
  pod "EVContactsPicker", :path => "../"
end

def testpods
  pod 'Quick', '~> 1'
  pod 'Nimble', '~> 5'
end

target 'EVContactsPicker_Example' do
  reusepods
end

target 'EVContactsPicker_Tests' do
  reusepods
  testpods
end
