source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EVContactsPicker_Example' do
  pod "EVContactsPicker", :path => "../"
end

target 'EVContactsPicker_Tests' do
  pod "EVContactsPicker", :path => "../"
end
