source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def reusepods
  pod "EVContactsPicker", :path => "../"
end

def testpods
  pod 'Quick', git: "https://github.com/Quick/Quick.git", branch: "swift-3.0"
  pod 'Nimble', '~> 5.0.0'
end

target 'EVContactsPicker_Example' do
  reusepods
end

target 'EVContactsPicker_Tests' do
  reusepods
  testpods
end
